name: Node Js - Workflow

on: 
  workflow_dispatch:
  push:
    branches: 
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing for Node JS 
    strategy:
      matrix: 
        nodejs-version: [18]
        operating-sys: [ubuntu-latest]

    runs-on: ${{ matrix.operating-sys }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install & Setup Node JS
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.nodejs-version }}
    
    - name: Caching Dependencies  
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    
    - name: Install Dependencies
      run: npm install 
    
    - name: Unit Testing 
      id: nodejs-unit-testing
      run: npm test 
    
    - name: Archive Test Result
      if: always() && (steps.nodejs-unit-testing.outcome == 'failure' || steps.nodejs-unit-testing.outcome == 'success')
      uses: actions/upload-artifact@v4
      with: 
      
        name: TestResult
        path: test-results.xml
  
  code-coverage:
    name: Code-Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node Js 
      uses: actions/setup-node@v6
      with:
        node-version: 18

    - name: Caching Dependencies  
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install 

    - name: Check Code Coverage 
      continue-on-error: true
      run: npm run coverage 

    - name: Archival Test Result
      uses: actions/upload-artifact@v4
      with: 
        name: Code-Coverage-Result
        path: coverage
        retention-days: 1

  docker:
    needs: [unit-testing, code-coverage]
    name: Docker Build & Push 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKER_USERNAME }}/solar:${{ github.sha }}
      
      - name: Docker Image Testing 
        run: |
          docker images 
          docker run --name solar-sys -d -p 3000:3000 -e MONGO_URI=$MONGO_URI -e MONGO_USERNAME=$MONGO_USERNAME -e MONGO_PASSWORD=$MONGO_PASSWORD ${{ vars.DOCKER_USERNAME }}/solar:${{ github.sha }} 
          
          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo $IP

          echo Testing Image URL 
          wget -q -O - 127.0.0.1:3000/live | grep live  

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/solar:${{ github.sha }}